version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kuriftu
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    command: postgres -c hba_file=/etc/postgresql/pg_hba.conf

  api:
    build: .
    environment:
      - DB_URL=postgres://user:password@db:5432/kuriftu?sslmode=disable
      - JWT_SECRET=1UMBt1BJ0-iGwpXRT8uzwgpKJEwSZW0yO5T5jT7IlD0=
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      - API_URL=/docs/swagger.yaml
    volumes:
      - ./docs:/usr/share/nginx/html/docs

volumes:
  db_data: