// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int32
	FirstName    string
	LastName     string
	Email        string
	PasswordHash string
	Phone        string
	UserType     string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	LastLoginAt  pgtype.Timestamptz
	IsActive     pgtype.Bool
}
